"""Added indexes on foreign key columns

Revision ID: e1037d2f8523
Revises: 
Create Date: 2024-11-29 18:14:56.128422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1037d2f8523'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actors', schema=None) as batch_op:
        batch_op.create_index('ix_actor_id', ['actor_id'], unique=False)

    with op.batch_alter_table('directors', schema=None) as batch_op:
        batch_op.create_index('ix_director_id', ['director_id'], unique=False)

    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.create_index('ix_genre_id', ['genre_id'], unique=False)

    with op.batch_alter_table('movie_actors', schema=None) as batch_op:
        batch_op.create_index('ix_movie_actor_actor_id', ['actor_id'], unique=False)
        batch_op.create_index('ix_movie_actor_movie_id', ['movie_id'], unique=False)

    with op.batch_alter_table('movie_directors', schema=None) as batch_op:
        batch_op.create_index('ix_movie_director_director_id', ['director_id'], unique=False)
        batch_op.create_index('ix_movie_director_movie_id', ['movie_id'], unique=False)

    with op.batch_alter_table('movie_genres', schema=None) as batch_op:
        batch_op.create_index('ix_movie_genre_genre_id', ['genre_id'], unique=False)
        batch_op.create_index('ix_movie_genre_movie_id', ['movie_id'], unique=False)

    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.create_index('ix_movie_id', ['movie_id'], unique=False)

    with op.batch_alter_table('user_favourites', schema=None) as batch_op:
        batch_op.create_index('ix_user_favourite_movie_id', ['movie_id'], unique=False)
        batch_op.create_index('ix_user_favourite_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('user_recommendations', schema=None) as batch_op:
        batch_op.create_index('ix_user_recommendation_movie_id', ['movie_id'], unique=False)
        batch_op.create_index('ix_user_recommendation_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_recommendations', schema=None) as batch_op:
        batch_op.drop_index('ix_user_recommendation_user_id')
        batch_op.drop_index('ix_user_recommendation_movie_id')

    with op.batch_alter_table('user_favourites', schema=None) as batch_op:
        batch_op.drop_index('ix_user_favourite_user_id')
        batch_op.drop_index('ix_user_favourite_movie_id')

    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_index('ix_movie_id')

    with op.batch_alter_table('movie_genres', schema=None) as batch_op:
        batch_op.drop_index('ix_movie_genre_movie_id')
        batch_op.drop_index('ix_movie_genre_genre_id')

    with op.batch_alter_table('movie_directors', schema=None) as batch_op:
        batch_op.drop_index('ix_movie_director_movie_id')
        batch_op.drop_index('ix_movie_director_director_id')

    with op.batch_alter_table('movie_actors', schema=None) as batch_op:
        batch_op.drop_index('ix_movie_actor_movie_id')
        batch_op.drop_index('ix_movie_actor_actor_id')

    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.drop_index('ix_genre_id')

    with op.batch_alter_table('directors', schema=None) as batch_op:
        batch_op.drop_index('ix_director_id')

    with op.batch_alter_table('actors', schema=None) as batch_op:
        batch_op.drop_index('ix_actor_id')

    # ### end Alembic commands ###
